# Generated by Django 5.1.1 on 2024-10-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_alter_user_id_auctionlisting_bid_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="image_url",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="auction_images/"),
        ),
    ]
